### ISSUE TITLE
Using uniqueName causes Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rajsite** [philips-software/protractor-junit-xml-plugin#27]
The default configuration has uniqueName set to true and when used with the following configuration:

```js
    // ...
    plugins: [
        {
            package: 'protractor-junit-xml-plugin',
            outdir: 'test_results/protractor'
        }
    ]
```

<details>
<summary>Results in the following error (click to expand):</summary>
<pre>
Executed 1 of 133 specs (1 FAILED) (132 SKIPPED) in 19 secs.
Inside plugin: browser.timestampForDir: undefined
JUnitXrayPlugin: CREATING DIR + test_results/protractor/browser-based-results
[15:33:53] I/plugins -           Fail:  protractor-junit-xml-plugin Plugin Tests
[15:33:53] E/plugins -          Failure during teardown: ENOENT: no such file or directory, open 'test_results/protractor/browser-based-results/metadata.json'
[15:33:53] E/plugins -          Error: ENOENT: no such file or directory, open 'test_results/protractor/browser-based-results/metadata.json'
                    at Object.openSync (fs.js:462:3)
                    at Object.writeFileSync (fs.js:1362:35)
                    at JUnitXmlPlugin.teardown (C:\<REMOVED>\node_modules\protractor-junit-xml-plugin\index.js:280:6)
                    at runMicrotasks (<anonymous>)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Cannot write JUnit xml
        ENOENT: no such file or directory, open 'C:\<REMOVED>\test_results\protractor\browser-based-results\chrome-1621024433945.xml'
[15:33:53] I/launcher - 0 instance(s) of WebDriver still running
[15:33:53] I/launcher - chrome #01 failed 2 test(s)
[15:33:53] I/launcher - overall: 2 failed spec(s)
[15:33:53] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.0.0 e2e: `npm run update-chrome-driver | ng e2e`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</pre>
</details>

If I explicitly set uniqueName to false then I do not get an error saving test results:
```js
    plugins: [
        {
            package: 'protractor-junit-xml-plugin',
            outdir: 'test_results/protractor',
            uniqueName: false
        }
    ]
```

Versions:
    "protractor": "5.4.4",
    "protractor-junit-xml-plugin": "2.0.0",

**Comment by msmithNI** [comment]
One workaround for this issue is to pre-create the test result directory, as well as the metadata.json file in the results directory, which can be done by adding this onPrepare() function in the protractor.conf export.config:
```js
beforeLaunch() {
        const testResultDirectory = path.resolve('test_results/protractor/browser-based-results');
        if (!fs.existsSync(testResultDirectory)) {
            fs.mkdirSync(testResultDirectory, { recursive: true });
        }
        const metadataFile = path.join(testResultDirectory, 'metadata.json');
        if (!fs.existsSync(metadataFile)) {
            fs.writeFileSync(metadataFile, '{"envProperties":{}}');
        }
    }
```

Note that metadata.json may have different contents depending on your Protractor setup. Ours just had an empty envProperties object as shown above (after a successful test run), so that's what we're using in onPrepare().

**Comment by arsal123** [comment]
Would you like to submit a Pull Request with this fix?
